account/urls.py
from django.conf.urls import url
from . import views

from django.conf import settings

from django.contrib.auth import views as auth_views

urlpatterns = [
    #url(r"^login/$", views.user_login, name="user_login"),
    url(r'^login/$', auth_views.login, name='user_login'),
    url(r'^new-login/$', auth_views.login, {"template_name": "account/login.html"}),
    url(r'^logout/$', auth_views.logout, {"template_name": "account/logout.html"}, name='user_logout'),
    url(r'^register/$', views.register, name='user_register'),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.blog_title, name="blog_title"),
    url(r'(?P<article_id>\d)/$', views.blog_article,name="blog_detail"),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
]

account/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    birth = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=20, null=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)

# Create your models here.

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class  BlogArticles(models.Model) :
    title = models.CharField(max_length=30)
    author = models.ForeignKey(User, related_name = "blog_posts")
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "email")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("passwords do not match.")
        return cd['password2']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("phone", "birth")

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login

from .forms import LoginForm, RegistrationForm, UserProfileForm

def user_login(request):
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])

            if user:
                login(request, user)
                return HttpResponse("Wellcome you. you have been authenticated successfully")
            else:
                return HttpResponse("Sorry. Your username or password is not right.")
        else:
            return HttpResponse("Invalid login")

    if request.method == "GET":
        login_form = LoginForm()
        return render(request, "account/login.html", {"form": login_form})

def register(request):
    if request.method == "POST":
        user_form = RegistrationForm(request.POST)
        userprofile_form = UserProfileForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            new_profile = userprofile_form.save(commit=False)
            new_profile.user = new_user
            new_profile.save()
            return HttpResponse("successfully")
        else:
            return HttpResponse("sorry, your can not register.")
    else:
        user_form = RegistrationForm()
        userprofile_form = UserProfileForm()
        return render(request, "account/register.html", {"form": user_form, "profile":userprofile_form})






# Create your views here.

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogArticles

# Create your views here.

def blog_title(request):
    blogs = BlogArticles.objects.all()
    return render(request, "blog/titles.html", {"blogs":blogs})

def blog_article(request, article_id):
    #article = BlogArticles.objects.get(id=article_id)
    article = get_object_or_404(BlogArticles, id=article_id)
    pub = article.publish
    return render(request, "blog/content.html", {"article":article, "publish":pub })

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang=” zh-cn”>
  <head>
    <meta charset=”utf-8”>
    <meta name=”viewport" content=”width=device-width, initial-scale=1”>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% include "footer.html" %}
    {% block javascript %}{% endblock %}
</body>
</html>

templates/blog/content.html
{% extends "base.html" %}
{% block title %}blog article{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
	<h1>{{ article.title }}</h1>
</div>
<div class="row">
	<div class="col-xs-12 col-md-8">
		<p class="text-center"><span>{{ article.author.username }}</span><span style="margin-left: 20px">{{ publish }}1</span></p>
		<div>{{ article.body }}</div>
	</div>
	<div class="col-xs-6 col-md-4">
		<h2>广告</h2>
		<p>跟老齐学：www.itdiffer.com</p>
		<img width="200px" src="http://www.mrwallpaper.com/wallpapers/Fluffy-Cat.jpg">
	</div>
</div>
{% endblock %}

templates/blog/titles.html
{% extends "base.html" %}
{% block title %}blog titles{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
	<h1>我的博客</h1>
</div>
<div class="row">
	<div class="col-xs-12 col-md-8">
		<ul>
			{% for blog in blogs %}
			<li><a href="{{ blog.id }}">{{ blog.title }}</a></li>
			{% endfor %}
		</ul>
	</div>
	<div class="col-xs-6 col-md-4">
		<h2>广告</h2>
		<p>跟老齐学：www.itdiffer.com</p>
	</div>
</div>
{% endblock %}

templates/footer.html
<div class="container">
    <p class="text-center">copy right www.itdiffer.com</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.itdiffer.com"><img src="{% static '/images/logo.png' %}" width="100px"></a>
	</div>
	<div>
	    <ul class="nav navbar-nav" role="navigation">
        <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
	    </ul>
	    <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
            {% if user.is_authenticated %}
            <li><a href="#">{{ user.username }}</a></li>
            <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
            {% endif %}
	    </ul>
	</div>
    </nav>
</div>